# Generated by Django 5.0.2 on 2024-02-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created',
        ),
    ]
